name: CI

on: [push, pull_request]

jobs:
  test:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        target:
          [
            x86_64-unknown-linux-gnu,
            x86_64-apple-darwin,
            x86_64-pc-windows-msvc,
            armv7-unknown-linux-gnueabihf,
            aarch64-unknown-linux-gnu,
          ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --verbose --target=${{ matrix.target }}

      - name: Run Tests
        run: cargo test --verbose --target=${{ matrix.target }}
