name: Deliver newspaper
on:
  schedule:
    # Run every day at 6AM
    - cron: "0 6 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: cargo run
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
