name: Manually trigger newspaper delivery
on:
  workflow_dispatch:
    inputs:
      email:
        description: "Enter recipient email"
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: cargo run --verbose
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_RELAY: ${{ secrets.SMTP_RELAY }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          MAIL_TO: ${{ github.event.inputs.logLevel || secrets.MAIL_TO }}
